//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlappyBird.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlappyBird.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlappyBird\BUILD_GUIDE.md.
        /// </summary>
        internal static string Build_GuideMd {
            get {
                return ResourceManager.GetString("Build_GuideMd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlappyBird\BuildStandalone.bat.
        /// </summary>
        internal static string BuildStandaloneBat {
            get {
                return ResourceManager.GetString("BuildStandaloneBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlappyBird\BuildStandalone.ps1.
        /// </summary>
        internal static string BuildStandalonePs1 {
            get {
                return ResourceManager.GetString("BuildStandalonePs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlappyBird\CreateIcon.ps1.
        /// </summary>
        internal static string CreateIconPs1 {
            get {
                return ResourceManager.GetString("CreateIconPs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flappy_Bird_1 {
            get {
                object obj = ResourceManager.GetObject("Flappy_Bird_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flappy_Bird_2 {
            get {
                object obj = ResourceManager.GetObject("Flappy_Bird_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FlappyBird {
            get {
                object obj = ResourceManager.GetObject("FlappyBird", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlappyBird\FlappyBird_Standalone.csproj.
        /// </summary>
        internal static string FlappyBird_StandaloneCsproj {
            get {
                return ResourceManager.GetString("FlappyBird_StandaloneCsproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PipeBody {
            get {
                object obj = ResourceManager.GetObject("PipeBody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PipeHead {
            get {
                object obj = ResourceManager.GetObject("PipeHead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlappyBird\QuickBuild.ps1.
        /// </summary>
        internal static string QuickBuildPs1 {
            get {
                return ResourceManager.GetString("QuickBuildPs1", resourceCulture);
            }
        }
    }
}
